storage: ./storage
plugins: ./plugins

web:
  title: Can4k personal NPM Registry

auth:
  htpasswd:
    file: ./htpasswd
    max_users: 1

packages:
  '@*/*':
    access: $all
    publish: $authenticated
    unpublish: $authenticated
    proxy: npmjs

  '**':
    access: $all
    publish: $authenticated
    unpublish: $authenticated
    proxy: npmjs

listen: 0.0.0.0:4001

uplinks:
  npmjs:
    url: https://registry.npmjs.org/
